use_frameworks!
platform :ios, '8.0'

target 'TYUIKit_Example' do
  pod 'YYImage'
  pod 'WoodPeckeriOS', :configurations => ['Debug']
  pod 'LookinServer', :configurations => ['Debug']

# for macOS project
# pod 'WoodpeckerMacOS', :configurations => ['Debug']
end

target 'TYUIKit_Tests' do
  pod 'TYUIKit', :path => '../'
# for macOS project
# pod 'WoodpeckerMacOS', :configurations => ['Debug']
end
